project:
  type: website
  output-dir: docs

website:
  title: "Morris Jones"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/shmers
      - text: CV
        href: assets/Morris_Jones_CV.pdf

format:
  html:
    theme: cosmo
    toc: true

execute:
  engine: python
  echo: true
  freeze: false
  python:
    path: py